Add instructions on how to build shared/dynamic library to the README
open-quantum-safe/liboqs pull request #1077
Opened 2021-08-20 11:29 UTC by Wandering-Consciousness

I was trying to build the .NET (C#) wrapper project (liboqs-dotnet) and its README referenced this repo/README to build the oqs shared library but I noticed the README only mentioned that a static library was built. The Golang wrapper did have instructions on how to do so, so for consistency and benefit to future readers, I updated this repo's one too.

No

* [ no] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

2021-08-20 17:40 UTC, baentsch requested changes
Thanks for this suggestion: Makes good sense, as not everyone reads/finds the Wiki. Two suggestions for improvement, though: Could you begin section 3 with "By default [the main build result...]" and continue with your addition as written? Second, it may be a good idea to put a hyperlink for BUILD_SHARED_LIBS (to https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs#build_shared_libs). Otherwise LGTM.

2021-08-22 03:01 UTC, Wandering-Consciousness commented
Thank you. I've made the changes you suggested.

2021-08-22 05:30 UTC, baentsch approved these changes
Thanks again. LGTM.

2021-08-23 18:09 UTC, dstebila approved these changes

2021-08-23 18:09 UTC, merged