Skip non-enabled algs in constant time tests
open-quantum-safe/liboqs pull request #1120
Opened 2021-11-04 17:37 UTC by christianpaquin

Skip non-enabled algs in constant time tests.

The current script depended on a `SKIP_ALGS` variable, that isn't documented and isn't set by cmake when using the `OQS_MINIMAL_BUILD ` build macro. I'm not sure if that code can safely replaced by the common helper check (as this PR does), or if it has a deeper purpose I don't understand.

2021-11-04 18:43 UTC, jschanck commented
Looks good to me. I prefer this solution to `SKIP_ALGS`. The change makes the `helpers.available_{sigs,kems}_by_name` decorator redundant. You could remove it, or add a new `helpers.enabled_{sigs,kems}_by_name` decorator instead.

2021-11-04 18:44 UTC, jschanck commented
Although it looks like @baentsch wrote `SKIP_ALGS`, not me. So maybe there's more to it.

2021-11-04 19:00 UTC, christianpaquin commented
> Although it looks like @baentsch wrote `SKIP_ALGS`, not me. So maybe there's more to it.

I've asked @baentsch to review :)

2021-11-05 06:17 UTC, baentsch requested changes
This approach surely is fine with me, but it needs to be complemented with suitable changes to CI: `SKIP_ALGS` parameter is [documented here](https://github.com/open-quantum-safe/liboqs/blob/468533abea77e7a7900ee9fdd82856ed25d06c2b/.circleci/config.yml#L97) and configured [here](https://github.com/open-quantum-safe/liboqs/blob/468533abea77e7a7900ee9fdd82856ed25d06c2b/.circleci/config.yml#L374). Reason were "irregular failures" of these algorithms in weekly tests. 
FYI, original issue: https://github.com/open-quantum-safe/liboqs/issues/1087  and original PR: https://github.com/open-quantum-safe/liboqs/pull/1089

2021-11-05 13:32 UTC, christianpaquin commented
Ah I see (my grep missed the `.circleci` folder, oops), you need skipping some algs even if they are compiled in the library. So these checks are not redundant, but complementary. I'll add back the SKIP_ALGS check.

2021-11-08 17:27 UTC, merged