Updated PQClean commit in `copy_from_upstream.yml`
open-quantum-safe/liboqs pull request #1359
Opened 2023-01-13 22:19 UTC by xvzcf

2023-01-14 06:54 UTC, baentsch commented on src/oqsconfig.h.cmake
> +
Code duplication?

2023-01-14 07:00 UTC, baentsch requested changes
LGTM except one set of apparently duplicated define's. However, I'd suggest to either manually add back the documentation items lost as per #1358 (that's what I did after running the script previously) or to first fix #1358 permanently.

2023-01-16 14:56 UTC, dstebila approved these changes

2023-01-16 15:15 UTC, xvzcf commented on src/oqsconfig.h.cmake
> +
Fixed.

2023-01-16 15:15 UTC, xvzcf commented
> LGTM except one set of apparently duplicated define's. However, I'd suggest to either manually add back the documentation items lost as per #1358 (that's what I did after running the script previously) or to first fix #1358 permanently.

I've manually added the documentation items back for now.

2023-01-16 15:27 UTC, baentsch approved these changes

2023-01-16 16:06 UTC, merged