correct free in test_kem/sig
open-quantum-safe/liboqs pull request #1399
Opened 2023-02-22 11:25 UTC by baentsch

Fixes #1398 

* [no] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

2023-02-22 16:02 UTC, thomwiggers requested changes
Looks pretty good, I just have one question about `sig` and `kem`. Are these pointers `NULL`-initialized?

2023-02-22 16:02 UTC, thomwiggers commented on tests/test_kem.c
> +	}
Do we even still need `kem != NULL`?

2023-02-22 16:02 UTC, thomwiggers commented on tests/test_sig.c
> +		}
do we still need `sig != NULL` here?

2023-02-22 16:03 UTC, thomwiggers commented
(Yes, they are `NULL`-initialized)

2023-02-22 17:10 UTC, baentsch commented on tests/test_sig.c
> +		}
no

2023-02-22 17:10 UTC, baentsch commented on tests/test_kem.c
> +	}
no

2023-02-23 15:24 UTC, dstebila approved these changes

2023-02-23 15:44 UTC, baentsch commented
@thomwiggers Please re-review to remove the merge blocker.

2023-02-23 16:24 UTC, thomwiggers approved these changes

2023-02-23 16:24 UTC, merged