Update Classic McEliece suppression files
open-quantum-safe/liboqs pull request #1541
Opened 2023-09-07 21:26 UTC by praveksharma

Updates suppression files to include potential leaks document in #1540.
Updates Classic McEliece advisories to include information about environment-specific constant time leaks.
Removes Classic-McEliece-6XX from weekly constant time test skip list. 

* [No] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [No] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

2023-09-07 21:33 UTC, praveksharma commented
@bhess I was hoping you could help me work on this issue, since I can't reproduce these errors locally. Could you check if Valgrind still complains about potential constant time leaks? 

It might be a good idea to add `--error-limit=no` to valgrind's [options list](https://github.com/open-quantum-safe/liboqs/blob/0dafd4f02c5a8fc000502ae51005a9962b671860/tests/test_constant_time.py#L193) to ensure valgrind reports all errors.

2023-09-08 05:56 UTC, baentsch reviewed
Thanks for keeping updating the suppression files for this algorithm family.

As this PR adds this (IMO very correct) advisory:

> Current implementation of the algorithm may not be constant-time

and looking at the length/extent of the suppression files and the above advisory I wonder whether it wouldn't be simpler to _completely_ exclude McEliece from constant time testing until someone states interest in giving McEliece the CT property (?) We have something similar [for BIKE](https://github.com/open-quantum-safe/liboqs/blob/main/tests/constant_time/kem/issues/bike_has_no_timing_protections) -- although I wonder whether this is (still) correct given there's no corresponding advisory for BIKE (???).

2023-09-08 09:01 UTC, bhess commented
> @bhess I was hoping you could help me work on this issue, since I can't reproduce these errors locally. Could you check if Valgrind still complains about potential constant time leaks?

I ran the tests and there is one error remaining. Seems to be all fine when adding one more rule.
```
{
   This implementation of Classic McEliece may not be constant time.
   Memcheck:Value8
   src:pk_gen.c:322
   # fun:PQCLEAN_MCELIECE348864_AVX2_pk_gen
   fun:PQCLEAN_MCELIECE348864_AVX2_crypto_kem_keypair
}
```

2023-09-11 17:32 UTC, praveksharma commented
> looking at the length/extent of the suppression files and the above advisory I wonder whether it wouldn't be simpler to _completely_ exclude McEliece from constant time testing until someone states interest in giving McEliece the CT property (?) 

> We have something similar [for BIKE](https://github.com/open-quantum-safe/liboqs/blob/main/tests/constant_time/kem/issues/bike_has_no_timing_protections) -- although I wonder whether this is (still) correct given there's no corresponding advisory for BIKE (???).

Looking through the [file history](https://github.com/open-quantum-safe/liboqs/commits/main/tests/constant_time/kem/issues/bike_has_no_timing_protections) for the BIKE suppression file, it looks like the advisories weren't updated when the suppression file was created. I've added a similar advisory for BIKE. 

I've updated the suppression file with the remaining error, we should be good to go.

2023-09-11 18:48 UTC, bhess reviewed
The McEliece ct-run looks ok on my test machine. Thanks for the update!

However, I didn't notice any BIKE errors. There also seem to be no issues registered in issues.json. I think [this file](https://github.com/open-quantum-safe/liboqs/blob/main/tests/constant_time/kem/issues/bike_has_no_timing_protections) could be removed since ct-fixes to BIKE were made in https://github.com/open-quantum-safe/liboqs/pull/1400.

2023-09-11 19:03 UTC, baentsch commented on .github/workflows/weekly.yml
> +            SKIP_ALGS: 'SPHINCS\+-SHA*, Classic-McEliece-(.)*, BIKE(.)*'
Skipping BIKE seems incorrect as per #1400.

2023-09-11 19:03 UTC, baentsch commented on docs/algorithms/kem/bike.md
> +This implementation of BIKE is not constant time.
Changing this only in the .MD and not the .YML will not survive the next execution of `copy_from_upstream.py`.

2023-09-11 19:04 UTC, baentsch commented on docs/algorithms/kem/classic_mceliece.md
> +- Current implementation of the algorithm may not be constant-time. Additionally, environment specific constant-time leaks may not be documented; please report potential constant-time leaks when foun
Same here. This ought to be in the YML (too) from which the MD is generated.

2023-09-11 19:05 UTC, baentsch requested changes
Beyond the single comment made I concur with @bhess that 

> [this file](https://github.com/open-quantum-safe/liboqs/blob/main/tests/constant_time/kem/issues/bike_has_no_timing_protections) could be removed since ct-fixes to BIKE were made in https://github.com/open-quantum-safe/liboqs/pull/1400.

2023-09-13 04:50 UTC, baentsch approved these changes

2023-09-13 12:46 UTC, merged