Add faces of contributors to README
open-quantum-safe/liboqs pull request #2022
Opened 2024-12-17 18:10 UTC by dstebila

I recently learned about [this tool](https://contrib.rocks/preview?repo=open-quantum-safe%2Fliboqs) to add pictures of contributors to the project README. Is it worth adding?

2024-12-17 21:45 UTC, SWilson4 approved these changes
Sure, why not?

2024-12-18 06:33 UTC, baentsch commented
> Sure, why not?

Here's a probably "weirdo" European answer: Privacy.

Seeing pictures IMO arguably is OK when one is logged in to GH, where viewers "reciprocate" making available their own avatar. Exporting that to everyone viewing the README (possibly a _much_ larger audience outside of GH) may not be to everyone's liking (I'm still undecided whether I'd object personally). Sure, the technical/legal "problem" lies with GH making these "pictures" available to external extraction and the tool to "amalgamate" them, but it'd be our decision to use these possibilities.

2024-12-18 06:55 UTC, baentsch commented
On second thought -- I don't like this: There's lots of "AI" crawling around stitching together an ever more complete picture of the world (if you pardon the pun) using publicly available user images. "Fine" if users gave their consent for this (say in return for cheap search results) but IMO not OK if one provided one's picture to (only) reciprocate to fellow developers also "opening up" within a walled garden (GH in this case).

Thus -unless hearing good arguments to the opposite- no approval from my side.

2024-12-18 06:58 UTC, baentsch requested changes
At least add reference to legal t's and c's explaining why this is legit.

2024-12-18 18:16 UTC, dstebila commented
Even for website visitors not logged in to Github, the images of the first 14 contributions are visible on https://github.com/open-quantum-safe/liboqs and the images of all contributors are visible on https://github.com/open-quantum-safe/liboqs/graphs/contributors.

That being said, I do not feel strongly enough to push for this; it was just a cute thing I saw on another project and wanted to suggest.

2024-12-19 08:42 UTC, baentsch commented
> Even for website visitors not logged in to Github, the images of the first 14 contributions are visible on https://github.com/open-quantum-safe/liboqs and the images of all contributors are visible on https://github.com/open-quantum-safe/liboqs/graphs/contributors.

Thanks for the pointer. Just logged out of GH to check (for the first time in many years, it seems :-). I'm not sure I like what I (still) see then. So your point is well taken, @dstebila . Withdrawing my "reservations" then. Do as you please.

2025-01-07 21:11 UTC, dstebila commented
Closing without merging due to lack of second approving review.

2025-01-07 21:11 UTC, closed without merging