Add OQS_MINIMAL_BUILD option
open-quantum-safe/liboqs pull request #903
Opened 2021-02-09 18:05 UTC by jschanck

This adds an option to build only the default KEM and Signature scheme. For example, with this patch, if you want to build liboqs with only the Kyber512 and Dilithium2 algorithms you can use:
```
cmake -GNinja -DOQS_MINIMAL_BUILD=ON -DOQS_KEM_DEFAULT=OQS_KEM_alg_kyber_512 -DOQS_SIG_DEFAULT=OQS_SIG_alg_dilithium_2 ..
```

This will build the exact match for the default kem and sig and also any "_aesni" or "_avx2" implementations that are supported by the platform.

Opening this PR, at @baentsch's recommendation, for discussion about whether this is a useful feature / what else we would like it to do.

2021-02-09 18:41 UTC, baentsch requested changes
As already stated, I like the option. But I'm missing a (CI) test run/config with this option on in this PR.

2021-02-10 11:19 UTC, baentsch commented
Thanks, @jschanck for https://github.com/open-quantum-safe/liboqs/pull/903/commits/5675c47f4f4da2589af57f4c3dc9ff46d0a7c123 : LGTM. PR/CI now gated by #899.

2021-02-10 14:24 UTC, baentsch commented
Thanks @bhess for #905. @jschanck could you please rebase and retry?

2021-02-12 14:58 UTC, baentsch approved these changes
Or are the arm tests triggered by an approval like this?

2021-02-12 15:00 UTC, jschanck commented
> I'm fine with the CI changes/platform removals -- but still don't understand what/who provides `testapproval`/unlocks the next stage(s).

Anyone on the team can click through to https://app.circleci.com/pipelines/github/open-quantum-safe, click the testapproval job marked in purple, then click "approve". That will run the remaining arm jobs and then you should be able to merge the PR.

2021-02-12 15:09 UTC, baentsch commented
> click the testapproval job marked in purple, then click "approve". That will run the remaining arm jobs and then you should be able to merge the PR

Just to check I finally got it: The idea here is that _anyone_ can do a quick PR CI, but only after a team member approved the long-running (say, arm) tests (and/or request naming the branch "...audit..." if such testing seems in order), CI + PR can conclude (?) One more click for team members doing PRs, but a much faster sanity check. OK for me.

2021-02-12 15:34 UTC, jschanck commented
> The idea here is that _anyone_ can do a quick PR CI, but only after a team member approved the long-running (say, arm) tests (and/or request naming the branch "...audit..." if such testing seems in order)

Exactly.

2021-02-13 15:53 UTC, merged